# Generated by Django 2.2.6 on 2019-10-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', models.TextField(verbose_name='分类描述正文')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='建议使用绝对路径', max_length=200, verbose_name='URL')),
                ('anchor_word', models.CharField(max_length=50, verbose_name='锚文字')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('does_follow', models.BooleanField(default=False, verbose_name='是否跟踪')),
            ],
            options={
                'verbose_name': '底部文字链接',
                'verbose_name_plural': '底部文字链接',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='建议使用绝对路径', max_length=200, verbose_name='URL')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('content', models.TextField(help_text='用 markdown 书写', verbose_name='正文')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('does_follow', models.BooleanField(default=False, verbose_name='是否跟踪')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
                ('pv', models.PositiveIntegerField(default=0)),
                ('uv', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '独立页面',
                'verbose_name_plural': '独立页面',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('sidebar_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最热文章'), (3, '最新文章')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(max_length=1024, verbose_name='内容')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', models.TextField(verbose_name='标签描述正文')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
                ('content', models.TextField(help_text='用 markdown 书写', verbose_name='正文')),
                ('pv', models.PositiveIntegerField(default=0)),
                ('uv', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.Category', verbose_name='分类')),
                ('tag', models.ManyToManyField(to='content.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-id'],
            },
        ),
    ]
