# Generated by Django 2.2.6 on 2019-11-30 23:40

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', models.TextField(help_text='用 markdown 书写', verbose_name='分类描述正文')),
                ('content_html', models.TextField(blank=True, editable=False, verbose_name='正文html代码')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-id'],
            },
            bases=(content.models.TranMarkdown, models.Model),
        ),
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(help_text='只能使用正整数且唯一', unique=True, verbose_name='序号')),
                ('title', models.CharField(help_text='不填则不显示标题', max_length=50, verbose_name='标题')),
                ('does_show_title', models.BooleanField(default=True, verbose_name='是否显示标题')),
                ('content_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最热文章'), (3, '最新文章')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, help_text='只有选择 HTML 时才需要填写内容', max_length=1024, verbose_name='内容')),
            ],
            options={
                'verbose_name': '首页内容区',
                'verbose_name_plural': '首页内容区',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(help_text='只能使用正整数且唯一', unique=True, verbose_name='序号')),
                ('url', models.CharField(help_text='建议使用绝对路径', max_length=200, verbose_name='URL')),
                ('anchor_word', models.CharField(max_length=50, verbose_name='锚文字')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('does_follow', models.BooleanField(default=False, verbose_name='是否跟踪')),
            ],
            options={
                'verbose_name': '底部文字链接',
                'verbose_name_plural': '底部文字链接',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('link_word', models.CharField(help_text='只能使用字母', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='URL字符串')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('content', models.TextField(help_text='用 markdown 书写', verbose_name='正文')),
                ('content_html', models.TextField(blank=True, editable=False, verbose_name='正文html代码')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('does_nav', models.BooleanField(default=False, verbose_name='是否添至导航栏')),
                ('does_follow', models.BooleanField(default=False, verbose_name='是否跟踪')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
            ],
            options={
                'verbose_name': '独立页面',
                'verbose_name_plural': '独立页面',
                'ordering': ['link_word'],
            },
            bases=(content.models.TranMarkdown, models.Model),
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(help_text='只能使用正整数且唯一', unique=True, verbose_name='序号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('does_show_title', models.BooleanField(default=True, verbose_name='是否显示标题')),
                ('sidebar_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最热文章'), (3, '最新文章')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, help_text='只有选择 HTML 时才需要填写内容', max_length=1024, verbose_name='内容')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', models.TextField(help_text='用 markdown 书写', verbose_name='标签描述正文')),
                ('content_html', models.TextField(blank=True, editable=False, verbose_name='正文html代码')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['-id'],
            },
            bases=(content.models.TranMarkdown, models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('desc', models.CharField(max_length=1024, verbose_name='摘要')),
                ('content', models.TextField(help_text='用 markdown 书写', verbose_name='正文')),
                ('content_html', models.TextField(blank=True, editable=False, verbose_name='正文html代码')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.Category', verbose_name='分类')),
                ('tag', models.ManyToManyField(to='content.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-create_time'],
            },
            bases=(content.models.TranMarkdown, models.Model),
        ),
    ]
