# Generated by Django 2.2.6 on 2019-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='不填则不显示标题', max_length=50, verbose_name='标题')),
                ('sidebar_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最热文章'), (3, '最新文章')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, help_text='只有选择 HTML 时才需要填写内容', max_length=1024, verbose_name='内容')),
            ],
            options={
                'verbose_name': '首页内容区',
                'verbose_name_plural': '首页内容区',
            },
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, help_text='只有选择 HTML 时才需要填写内容', max_length=1024, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(blank=True, help_text='不填则不显示标题', max_length=50, verbose_name='标题'),
        ),
    ]
