# Generated by Django 2.2.6 on 2019-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20191029_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='does_nav',
            field=models.BooleanField(default=False, verbose_name='是否添至导航栏'),
        ),
    ]
