# Generated by Django 2.2.6 on 2019-10-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_page_does_nav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
