# Generated by Django 2.2.6 on 2019-11-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20191101_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexcontent',
            options={'ordering': ['order_number'], 'verbose_name': '首页内容区', 'verbose_name_plural': '首页内容区'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order_number'], 'verbose_name': '底部文字链接', 'verbose_name_plural': '底部文字链接'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['order_number'], 'verbose_name': '侧边栏', 'verbose_name_plural': '侧边栏'},
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='只能使用正整数且唯一', verbose_name='序号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='只能使用正整数且唯一', verbose_name='序号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebar',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='只能使用正整数且唯一', verbose_name='序号'),
            preserve_default=False,
        ),
    ]
