# Generated by Django 2.2.6 on 2019-11-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20191101_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcontent',
            name='order_number',
            field=models.PositiveSmallIntegerField(help_text='只能使用正整数且唯一', unique=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='link',
            name='order_number',
            field=models.PositiveSmallIntegerField(help_text='只能使用正整数且唯一', unique=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='order_number',
            field=models.PositiveSmallIntegerField(help_text='只能使用正整数且唯一', unique=True, verbose_name='序号'),
        ),
    ]
