# Generated by Django 2.2.6 on 2019-11-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20191101_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
        migrations.AddField(
            model_name='category',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
        migrations.AddField(
            model_name='tag',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(help_text='用 markdown 书写', verbose_name='分类描述正文'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.TextField(help_text='用 markdown 书写', verbose_name='标签描述正文'),
        ),
    ]
