# Generated by Django 2.2.6 on 2019-11-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20191101_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['link_word'], 'verbose_name': '独立页面', 'verbose_name_plural': '独立页面'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
